name: ColorTime
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18371
title: ColorTime_LOGO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#D0D0D0'
    - '#616161'
    - '#8C8C8C'
    - '#B1B1B1'
  brandStrength: 1
  lightness: 0.06509031
  saturation: 0.4815756
  rhythmicContrast: 0.2283195
purpose: []
