name: ColorTime
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18371
title: ColorTime Post Production Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e8eb'
    - '#141414'
    - '#a2a2a4'
    - '#e1752d'
    - '#ffb468'
  brandStrength: 1
  lightness: 0.06509031
  saturation: 0.4815756
  rhythmicContrast: 0.75
purpose: []
